### ISSUE TITLE
`api` package (to be imported by others)

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#106]
To become a better utility and also to become a package/library we need to separate core logic into a `api` package, so the main will become really bare and easy to understand. Also other people could include `api` as a Golang package [not just using CLI] with this.

## Todo
- [x] Provide API PoC https://github.com/ivanilves/lstags/pull/112
- [x] Provide reliable integration tests for API https://github.com/ivanilves/lstags/pull/119
- [x] Refactor API to get rid of PoC state https://github.com/ivanilves/lstags/pull/117
- [x] Provide versioning of API (so developers may develop safely) https://github.com/ivanilves/lstags/pull/114
- [x] Provide basic API documentation
- [x] Build a PoC application using `v1` lstags API
- [x] Reach out to the new potential stakeholders

**Comment by ivanilves** [comment]
Done!
