### ISSUE TITLE
Better world: First refactor of the lstags

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#63]
We have reached the state when we need to:
* stop adding new functionality for a while.
* work more on automated testing, code quality and various fixes.
* add performance, benefit more of concurrency Golang gives us [almost] for free. 

### TODO
- [x] **Add black-box shell tests for "image pull" functionality.**
- [x] Fix lame ("double"?) help messages.
- [x] Make registry and operations event more concurrent.
- [x] **Fix authenticated pull.**

# GIF
![](https://media.giphy.com/media/jqY3V9oF889SE/giphy.gif)

**Comment by ivanilves** [comment]
https://github.com/ivanilves/lstags/pull/65
*  Make registry and operations event more concurrent.

**Comment by ivanilves** [comment]
https://github.com/ivanilves/lstags/pull/66
*  Fix lame ("double"?) help messages.

**Comment by ivanilves** [comment]
:bulb: We need to test pull of some scratch-based repo inside our integration tests!

**Comment by ivanilves** [comment]
https://github.com/ivanilves/lstags/pull/70
*  Fix authenticated pull

**Comment by ivanilves** [comment]
I would better get back to milestones for this...

**Comment by ivanilves** [comment]
Here we work to finish the issue: https://github.com/ivanilves/lstags/pull/71

**Comment by ivanilves** [comment]
I consider this done. Scope is reduced, but it is done.
